name: Myfirstworkflow

on: push

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: putting code on runner
        run : git clone https://github.com/iamvinugouroji/Github-Success-2026.git

      - name : cheking the code
        run  : |
          cd Github-Success-2026 
          ls -la

      - name : running the script
        run : |
            chmod +x new.sh
            ./new.sh
            



    