name: Build and Push

on: workflow_dispatch
 

jobs:
  buildandpush:
    runs-on: [self-hosted, prd]

    steps:
      - name: checkout code 
        run: actions/checkout@v3

      - name: Login to Docker Hub 
        run: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
               

      - name: setup QEMU
        run: docker/setup-qemu-action@v2
    
      - name: setup Docker Buildx
        run: docker/setup-buildx-action@v2

      - name: build and push
        run: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/appbb10-2:latest